import type { Candidate } from '@/features/candidates/types/candidate';

export const seedMockCandidates: Candidate[] = [
  {
    id: 'cand-1001',
    firstName: 'Ava',
    lastName: 'Kowalski',
    email: 'ava.kowalski@example.com',
    phone: '+48500100200',
    country: 'Poland',
    highestDegree: 'master',
    universityName: 'University of Warsaw',
    graduationYear: 2018,
    yearsOfProfessionalExperience: 6,
    currentEmployer: 'Northwind Digital',
    program: 'level_2',
    preferredExamWindow: '2026-11',
    status: 'eligible',
    registrationDate: '2026-05-14T10:30:00.000Z',
  },
  {
    id: 'cand-1002',
    firstName: 'Marek',
    lastName: 'Nowak',
    email: 'marek.nowak@example.com',
    phone: '+48501200300',
    country: 'Poland',
    highestDegree: 'bachelor',
    universityName: 'AGH University of Krakow',
    graduationYear: 2024,
    yearsOfProfessionalExperience: 1,
    program: 'level_1',
    preferredExamWindow: '2026-08',
    status: 'pending',
    registrationDate: '2026-05-16T08:15:00.000Z',
  },
  {
    id: 'cand-1003',
    firstName: 'Sofia',
    lastName: 'Martinez',
    email: 'sofia.martinez@example.com',
    phone: '+34600111222',
    country: 'Spain',
    highestDegree: 'phd',
    universityName: 'Complutense University of Madrid',
    graduationYear: 2015,
    yearsOfProfessionalExperience: 9,
    currentEmployer: 'Iberia Systems',
    program: 'level_3',
    preferredExamWindow: '2026-12',
    status: 'eligible',
    registrationDate: '2026-05-12T14:45:00.000Z',
  },
  {
    id: 'cand-1004',
    firstName: 'Jonas',
    lastName: 'Weber',
    email: 'jonas.weber@example.com',
    phone: '+49151222333',
    country: 'Germany',
    highestDegree: 'other',
    universityName: 'Berlin Professional Institute',
    graduationYear: 2023,
    yearsOfProfessionalExperience: 2,
    program: 'level_1',
    preferredExamWindow: '2026-09',
    status: 'ineligible',
    registrationDate: '2026-05-10T11:20:00.000Z',
  },
  {
    id: 'cand-1005',
    firstName: 'Elena',
    lastName: 'Meyer',
    email: 'elena.meyer@example.com',
    country: 'Germany',
    highestDegree: 'master',
    universityName: 'Technical University of Munich',
    graduationYear: 2016,
    yearsOfProfessionalExperience: 8,
    currentEmployer: 'Alpine Analytics',
    program: 'level_2',
    preferredExamWindow: '2026-10',
    status: 'eligible',
    registrationDate: '2026-05-08T09:00:00.000Z',
  },
  {
    id: 'cand-1006',
    firstName: 'Priya',
    lastName: 'Sharma',
    email: 'priya.sharma@example.com',
    phone: '+919876543210',
    country: 'India',
    highestDegree: 'bachelor',
    universityName: 'Indian Institute of Science',
    graduationYear: 2025,
    yearsOfProfessionalExperience: 0,
    program: 'level_1',
    preferredExamWindow: '2026-08',
    status: 'pending',
    registrationDate: '2026-05-17T16:30:00.000Z',
  },
  {
    id: 'cand-1007',
    firstName: 'Lucas',
    lastName: 'Dupont',
    email: 'lucas.dupont@example.com',
    country: 'France',
    highestDegree: 'bachelor',
    universityName: 'University of Lyon',
    graduationYear: 2019,
    yearsOfProfessionalExperience: 5,
    currentEmployer: 'Rhône Labs',
    program: 'level_1',
    preferredExamWindow: '2026-11',
    status: 'withdrawn',
    registrationDate: '2026-05-05T13:10:00.000Z',
  },
  {
    id: 'cand-1008',
    firstName: 'Hannah',
    lastName: 'Clark',
    email: 'hannah.clark@example.com',
    phone: '+14155550123',
    country: 'United States',
    highestDegree: 'master',
    universityName: 'Boston University',
    graduationYear: 2014,
    yearsOfProfessionalExperience: 10,
    currentEmployer: 'Harbor Capital Tech',
    program: 'level_3',
    preferredExamWindow: '2026-12',
    status: 'eligible',
    registrationDate: '2026-05-01T18:45:00.000Z',
  },
  {
    id: 'cand-1009',
    firstName: 'Noah',
    lastName: 'Berg',
    email: 'noah.berg@example.com',
    country: 'Sweden',
    highestDegree: 'bachelor',
    universityName: 'KTH Royal Institute of Technology',
    graduationYear: 2020,
    yearsOfProfessionalExperience: 4,
    program: 'level_1',
    preferredExamWindow: '2026-09',
    status: 'eligible',
    registrationDate: '2026-04-28T12:00:00.000Z',
  },
  {
    id: 'cand-1010',
    firstName: 'Amira',
    lastName: 'Haddad',
    email: 'amira.haddad@example.com',
    country: 'United Arab Emirates',
    highestDegree: 'master',
    universityName: 'American University of Sharjah',
    graduationYear: 2017,
    yearsOfProfessionalExperience: 7,
    currentEmployer: 'Gulf FinTech',
    program: 'level_2',
    preferredExamWindow: '2026-10',
    status: 'pending',
    registrationDate: '2026-04-20T09:30:00.000Z',
  },
];
